# Generated by Django 3.0.3 on 2020-08-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_material'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
