# Generated by Django 3.0.3 on 2020-08-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_gradedassignment_submitted'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gradedassignment',
            constraint=models.UniqueConstraint(fields=('assignment', 'user'), name='unique_for_user'),
        ),
    ]
