# Generated by Django 3.0.3 on 2020-09-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_auto_20200823_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=240),
        ),
    ]
